# Atelier Pandas – Données IoT

Préparation et analyse de mesures issues de capteurs IoT (température, humidité, pression, consommation) avant transmission à un système de Machine Learning.

## Partie 1 – Series

### 1) Créer une Series contenant 4 températures

In [1]:
import pandas as pd

serie_temp = pd.Series([24.5, 25.1, 26.3, 27.8])
serie_temp

0    24.5
1    25.1
2    26.3
3    27.8
dtype: float64

### 2) Afficher son index

In [2]:
serie_temp.index

RangeIndex(start=0, stop=4, step=1)

### 3) Afficher la 1ère valeur

In [3]:
serie_temp.iloc[0]

np.float64(24.5)

### 4) Afficher la dernière valeur

In [4]:
serie_temp.iloc[-1]

np.float64(27.8)

### 5) Créer, de deux façons différentes, une Series de 4 températures avec les heures de mesure 12h, 13h, 14h et 15h comme index

**Méthode 1 :** passer l'index en paramètre

In [5]:
temps = [24.5, 25.1, 26.3, 27.8]
heures = [12, 13, 14, 15]

serie_heures = pd.Series(temps, index=heures)
serie_heures

12    24.5
13    25.1
14    26.3
15    27.8
dtype: float64

**Méthode 2 :** passer un dictionnaire

In [6]:
serie_heures2 = pd.Series({12: 24.5, 13: 25.1, 14: 26.3, 15: 27.8})
serie_heures2

12    24.5
13    25.1
14    26.3
15    27.8
dtype: float64

### 6) Afficher la 1ère et la dernière valeur

In [7]:
premiere = serie_heures.iloc[0]
derniere = serie_heures.iloc[-1]
print(f"1ère valeur : {premiere}")
print(f"Dernière valeur : {derniere}")

1ère valeur : 24.5
Dernière valeur : 27.8

## Partie 2 – DataFrame

### 1) Créer et afficher le dataframe `df_test` à partir du dictionnaire

In [8]:
data = {
    "capteur": ["C001", "C002", "C003"],
    "temperature": [24.5, 25.1, 26.3],
    "humidite": [65, 67, 70]
}

df_test = pd.DataFrame(data)
df_test

  capteur  temperature  humidite
0    C001         24.5        65
1    C002         25.1        67
2    C003         26.3        70

### 2) Importer le dataset `mesures_capteurs.csv` dans le dataframe `df`

In [9]:
df = pd.read_csv("../data/mesures_capteurs.csv")
df

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK
...,...,...,...,...,...,...,...,...,...
600,M0072,2026-01-07 23:00:00,C012,B004,23.67,60.28,1015.11,282.36,OK
601,M0107,2026-01-09 10:00:00,C011,B004,24.34,61.42,1019.43,357.43,OK
602,M0271,2026-01-16 06:00:00,C007,B003,23.73,63.49,1016.46,152.79,OK
603,M0436,2026-01-23 03:00:00,C004,B002,24.83,79.77,1017.05,170.97,OK
604,M0103,2026-01-09 06:00:00,C007,B003,17.02,52.04,1001.14,44.99,OK

### 3) Afficher les dimensions de `df`

In [10]:
print(f"{df.shape[0]} lignes et {df.shape[1]} colonnes")

605 lignes et 9 colonnes

## Partie 3 – Exploration

Dans la suite de l'atelier, on travaille avec le dataframe `df`.

### 1) Afficher les premières lignes

In [11]:
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

### 2) Afficher les 10 premières lignes

In [12]:
df.head(10)

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK
5,M0595,2026-01-29 18:00:00,C007,B003,24.51,58.01,1013.34,146.10,OK
6,M0011,2026-01-05 10:00:00,C011,B004,29.23,70.43,1007.68,290.45,OK
7,M0132,2026-01-10 11:00:00,C012,B004,31.21,60.57,1024.64,285.92,OK
8,M0444,2026-01-23 11:00:00,C012,B004,23.11,82.06,1021.96,293.36,OK
9,M0087,2026-01-08 14:00:00,C003,B001,28.85,44.37,1008.27,206.59,OK

### 3) Afficher les dernières lignes

In [13]:
df.tail()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
600,M0072,2026-01-07 23:00:00,C012,B004,23.67,60.28,1015.11,282.36,OK
601,M0107,2026-01-09 10:00:00,C011,B004,24.34,61.42,1019.43,357.43,OK
602,M0271,2026-01-16 06:00:00,C007,B003,23.73,63.49,1016.46,152.79,OK
603,M0436,2026-01-23 03:00:00,C004,B002,24.83,79.77,1017.05,170.97,OK
604,M0103,2026-01-09 06:00:00,C007,B003,17.02,52.04,1001.14,44.99,OK

### 4) Afficher le nombre de lignes

In [14]:
df.shape[0]

605

### 5) Afficher le nombre de colonnes

In [15]:
df.shape[1]

9

### 6) Afficher les noms des colonnes

In [16]:
df.columns

Index(['id_mesure', 'date_heure', 'id_capteur', 'batiment', 'temperature',
       'humidite', 'pression', 'consommation', 'etat'],
      dtype='object')

### 7) Afficher les informations générales

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_mesure     605 non-null    object
 1   date_heure    605 non-null    object
 2   id_capteur    605 non-null    object
 3   batiment      605 non-null    object
 4   temperature   599 non-null    float64
 5   humidite      600 non-null    float64
 6   pression      600 non-null    float64
 7   consommation  600 non-null    float64
 8   etat          601 non-null    object
dtypes: float64(4), object(5)
memory usage: 42.7+ KB

### 8) Afficher les statistiques descriptives

In [18]:
df.describe()

       temperature   humidite     pression  consommation
count   599.000000  600.00000   600.000000    600.000000
mean     24.878314   64.92620  1012.221900    208.675417
std       4.059576   10.76905    10.599042     72.243567
min     -18.500000   28.52000   850.000000     18.120000
25%      22.570000   58.17250  1006.790000    160.177500
50%      24.860000   65.37500  1012.855000    206.150000
75%      27.275000   71.61500  1017.827500    254.127500
max      58.700000  145.00000  1038.430000    875.000000

## Partie 4 – Sélection

### 1) Sélectionner la colonne "temperature"

In [19]:
df["temperature"]

0      25.46
1      24.00
2      25.82
3      28.23
4      20.58
       ...
600    23.67
601    24.34
602    23.73
603    24.83
604    17.02
Name: temperature, Length: 605, dtype: float64

### 2) Sélectionner les colonnes "temperature", "humidite", "pression" et "consommation"

In [20]:
df[["temperature", "humidite", "pression", "consommation"]]

     temperature  humidite  pression  consommation
0          25.46     58.06   1008.95        287.28
1          24.00     79.73    993.39        116.20
2          25.82     54.47   1010.32        288.50
3          28.23     69.39   1019.62        136.65
4          20.58     53.80   1016.58        182.62
..           ...       ...       ...           ...
600        23.67     60.28   1015.11        282.36
601        24.34     61.42   1019.43        357.43
602        23.73     63.49   1016.46        152.79
603        24.83     79.77   1017.05        170.97
604        17.02     52.04   1001.14         44.99

[605 rows x 4 columns]

### 3) Sélectionner les 5 premières lignes avec `loc`

In [21]:
df.loc[0:4]

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

### 4) Sélectionner les 5 premières lignes et les 4 premières colonnes avec `iloc`

In [22]:
df.iloc[0:5, 0:4]

  id_mesure           date_heure id_capteur batiment
0     M0413  2026-01-22 04:00:00       C005     B002
1     M0290  2026-01-17 01:00:00       C002     B001
2     M0077  2026-01-08 04:00:00       C005     B002
3     M0079  2026-01-08 06:00:00       C007     B003
4     M0183  2026-01-12 14:00:00       C003     B001

## Partie 5 – Manipulation des colonnes

### 1) Ajouter la colonne "temperature_fahrenheit"

In [23]:
df["temperature_fahrenheit"] = df["temperature"] * 9 / 5 + 32
df[["temperature", "temperature_fahrenheit"]].head()

   temperature  temperature_fahrenheit
0        25.46                  77.828
1        24.00                  75.200
2        25.82                  78.476
3        28.23                  82.814
4        20.58                  69.044

### 2) Ajouter la colonne "niveau_temperature" (Élevée si température > 30, sinon Normale) avec la méthode where() de numpy

In [24]:
import numpy as np

df["niveau_temperature"] = np.where(df["temperature"] > 30, "Élevée", "Normale")
df["niveau_temperature"].value_counts()

niveau_temperature
Normale    559
Élevée      46
Name: count, dtype: int64

### 3) Renommer la colonne "humidite" en "humidite_relative"

In [25]:
df = df.rename(columns={"humidite": "humidite_relative"})
df.columns

Index(['id_mesure', 'date_heure', 'id_capteur', 'batiment', 'temperature',
       'humidite_relative', 'pression', 'consommation', 'etat',
       'temperature_fahrenheit', 'niveau_temperature'],
      dtype='object')

### 4) Supprimer la colonne "temperature_fahrenheit"

In [26]:
df = df.drop(columns=["temperature_fahrenheit"])
df.columns

Index(['id_mesure', 'date_heure', 'id_capteur', 'batiment', 'temperature',
       'humidite_relative', 'pression', 'consommation', 'etat',
       'niveau_temperature'],
      dtype='object')

## Partie 6 – Filtrage

### 1) Lignes telles que température > 30

In [27]:
df_filtre = df[df["temperature"] > 30]
print(f"{len(df_filtre)} lignes")
df_filtre[["temperature", "batiment"]].head()

46 lignes

    temperature batiment
7         31.21     B004
43        34.72     B004
47        32.46     B004
63        31.19     B002
79        31.74     B004

### 2) Lignes telles que température > 30 et humidité > 70

In [28]:
df_filtre2 = df[(df["temperature"] > 30) & (df["humidite_relative"] > 70)]
print(f"{len(df_filtre2)} lignes")
df_filtre2[["temperature", "humidite_relative", "batiment"]].head()

14 lignes

     temperature  humidite_relative batiment
47         32.46              72.31     B004
88         30.06              75.30     B004
129        33.60              79.80     B002
145        30.57              71.26     B004
165        33.01              73.24     B004

## Partie 7 – Tri

### 1) `df_trie1` : tri par température croissante

In [29]:
df_trie1 = df.sort_values("temperature")
df_trie1[['temperature', 'batiment']].head(10)

     temperature batiment
487       -18.50     B004
245        14.11     B003
258        15.49     B003
249        16.04     B003
59         16.77     B001
67         16.87     B001
604        17.02     B003
450        17.13     B001
386        17.67     B003
506        17.67     B002

### 2) `df_trie2` : tri par température décroissante

In [30]:
df_trie2 = df.sort_values("temperature", ascending=False)
df_trie2[['temperature', 'batiment']].head(10)

     temperature batiment
502        58.70     B004
43         34.72     B004
129        33.60     B002
211        33.29     B004
165        33.01     B004
118        32.90     B002
520        32.72     B001
438        32.56     B002
47         32.46     B004
169        32.36     B002

### 3) `top10` : les 10 températures les plus élevées

In [31]:
top10 = df.nlargest(10, "temperature")
top10[['temperature', 'batiment', 'id_capteur']]

     temperature batiment id_capteur
502        58.70     B004       C012
43         34.72     B004       C011
129        33.60     B002       C004
211        33.29     B004       C010
165        33.01     B004       C011
118        32.90     B002       C005
520        32.72     B001       C003
438        32.56     B002       C006
47         32.46     B004       C010
169        32.36     B002       C006

### 4) Tri par colonnes "batiment" (croissant) et "temperature" (décroissant)

In [32]:
df_trie3 = df.sort_values(["batiment", "temperature"], ascending=[True, False])
df_trie3[['batiment', 'temperature']].head(15)

    batiment  temperature
520     B001        32.72
447     B001        31.15
224     B001        30.84
500     B001        30.39
9       B001        28.85
467     B001        28.85
567     B001        28.71
85      B001        28.41
293     B001        28.31
263     B001        28.11
400     B001        28.09
166     B001        28.01
70      B001        27.91
110     B001        27.88
28      B001        27.87

## Partie 8 – Analyse

### 1) Consommation moyenne par bâtiment

In [33]:
df.groupby("batiment")["consommation"].mean()

batiment
B001    177.870927
B002    221.785333
B003    153.191000
B004    282.552282
Name: consommation, dtype: float64

### 2) Minimum, maximum, moyenne et écart-type de la température par bâtiment

In [34]:
df.groupby("batiment")["temperature"].agg(["min", "max", "mean", "std"])

            min    max       mean       std
batiment
B001      16.77  32.72  23.578824  2.961211
B002      17.67  33.60  25.778000  2.951828
B003      14.11  31.74  23.013699  2.983902
B004     -18.50  58.70  27.119000  5.367361

### 3) Par bâtiment : maximum et moyenne de la température et de la consommation

In [35]:
df.groupby("batiment").agg({"temperature": ["max", "mean"], "consommation": ["max", "mean"]})

         temperature            consommation
                 max       mean          max        mean
batiment
B001           32.72  23.578824       294.72  177.870927
B002           33.60  25.778000       335.20  221.785333
B003           31.74  23.013699       875.00  153.191000
B004           58.70  27.119000       411.12  282.552282

### 4) Température moyenne globale

In [36]:
df["temperature"].mean()

np.float64(24.87831385642738)

### 5) Température maximale

In [37]:
df["temperature"].max()

58.7

### 6) Consommation totale

In [38]:
df["consommation"].sum()

np.float64(125205.25)

### 7) Quel bâtiment consomme le plus en moyenne ?

In [39]:
moyennes = df.groupby("batiment")["consommation"].mean()
print(moyennes)
print(f"Le bâtiment qui consomme le plus en moyenne : {moyennes.idxmax()}")

batiment
B001    177.870927
B002    221.785333
B003    153.191000
B004    282.552282
Name: consommation, dtype: float64
Le bâtiment qui consomme le plus en moyenne : B004

### 8) Nombre d'alertes par bâtiment

In [40]:
df[df["etat"] == "ALERTE"].groupby("batiment").size()

batiment
B001     2
B002     7
B003     5
B004    15
dtype: int64

## Partie 9 – Gestion des valeurs manquantes

### 1) Nombre de valeurs manquantes par colonne

In [41]:
df.isna().sum()

id_mesure             0
date_heure            0
id_capteur            0
batiment              0
temperature           6
humidite_relative     5
pression              5
consommation          5
etat                  4
niveau_temperature    0
dtype: int64

### 2) Nombre total de valeurs manquantes

In [42]:
df.isna().sum().sum()

np.int64(25)

### 3) Taux de valeurs manquantes

In [43]:
df.isna().mean()

id_mesure             0.000000
date_heure            0.000000
id_capteur            0.000000
batiment              0.000000
temperature           0.009917
humidite_relative     0.008264
pression              0.008264
consommation          0.008264
etat                  0.006612
niveau_temperature    0.000000
dtype: float64

### 4) Lignes contenant des valeurs manquantes

In [44]:
df[df.isna().any(axis=1)]

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
14,M0056,2026-01-07 07:00:00,C008,B003,22.33,67.42,1014.41,101.20,NaN,Normale
30,M0073,2026-01-08 00:00:00,C001,B001,23.12,63.97,NaN,186.87,OK,Normale
91,M0473,2026-01-24 16:00:00,C005,B002,21.32,70.43,1021.20,194.76,NaN,Normale
128,M0300,2026-01-17 11:00:00,C012,B004,23.32,55.73,NaN,232.38,OK,Normale
139,M0345,2026-01-19 08:00:00,C009,B003,NaN,66.77,1015.33,216.31,OK,Normale
146,M0118,2026-01-09 21:00:00,C010,B004,30.32,NaN,1015.78,261.68,OK,Élevée
149,M0034,2026-01-06 09:00:00,C010,B004,28.91,NaN,1001.23,234.30,OK,Normale
163,M0019,2026-01-05 18:00:00,C007,B003,NaN,69.97,1014.14,181.07,OK,Normale
196,M0372,2026-01-20 11:00:00,C012,B004,29.33,56.91,1020.02,NaN,OK,Normale
215,M0204,2026-01-13 11:00:00,C012,B004,NaN,59.96,1007.98,294.02,OK,Normale
270,M0334,2026-01-18 21:00:00,C010,B004,29.63,67.70,1016.30,363.68,NaN,Normale
303,M0584,2026-01-29 07:00:00,C008,B003,23.78,64.66,NaN,153.81,OK,Normale
307,M0169,2026-01-12 00:00:00,C001,B001,21.86,51.83,NaN,195.72,OK,Normale
323,M0391,2026-01-21 06:00:00,C007,B003,21.82,NaN,1006.47,98.39,OK,Normale
459,M0143,2026-01-10 22:00:00,C011,B004,28.65,66.88,1001.41,NaN,OK,Normale
476,M0527,2026-01-26 22:00:00,C011,B004,26.16,NaN,1024.21,232.87,OK,Normale
490,M0227,2026-01-14 10:00:00,C011,B004,25.13,85.60,1011.20,NaN,ALERTE,Normale
491,M0449,2026-01-23 16:00:00,C005,B002,26.82,61.99,NaN,215.34,OK,Normale
511,M0506,2026-01-26 01:00:00,C002,B001,24.04,57.10,1014.04,NaN,OK,Normale
513,M0490,2026-01-25 09:00:00,C010,B004,NaN,52.97,1010.71,253.63,OK,Normale
526,M0015,2026-01-05 14:00:00,C003,B001,23.17,79.95,1006.07,NaN,OK,Normale
536,M0252,2026-01-15 11:00:00,C012,B004,27.01,NaN,1018.36,263.13,OK,Normale
548,M0572,2026-01-28 19:00:00,C008,B003,NaN,68.63,1018.58,252.48,OK,Normale
556,M0092,2026-01-08 19:00:00,C008,B003,NaN,79.81,1007.05,113.00,OK,Normale
572,M0190,2026-01-12 21:00:00,C010,B004,24.24,73.55,1018.12,299.91,NaN,Normale

### 5) Remplacer les valeurs manquantes de température et d'humidité par les moyennes

In [45]:
df["temperature"] = df["temperature"].fillna(df["temperature"].mean())
df["humidite_relative"] = df["humidite_relative"].fillna(df["humidite_relative"].mean())
df[["temperature", "humidite_relative"]].isna().sum()

temperature          0
humidite_relative    0
dtype: int64

### 6) Remplacer les valeurs manquantes de consommation par la médiane

In [46]:
df["consommation"] = df["consommation"].fillna(df["consommation"].median())
df["consommation"].isna().sum()

np.int64(0)

### 7) Remplacer les valeurs manquantes de "etat" par "INCONNU"

In [47]:
df["etat"] = df["etat"].fillna("INCONNU")
print(df["etat"].isna().sum(), "valeurs manquantes restantes")
df.isna().sum()

0 valeurs manquantes restantes

id_mesure             0
date_heure            0
id_capteur            0
batiment              0
temperature           0
humidite_relative     0
pression              5
consommation          0
etat                  0
niveau_temperature    0
dtype: int64

## Partie 10 – Gestion des doublons

### 1) Nombre de doublons

In [48]:
df.duplicated().sum()

np.int64(5)

### 2) Afficher les doublons

In [49]:
df[df.duplicated()]

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
183,M0599,2026-01-29 22:00:00,C011,B004,22.02,68.09,1005.90,227.81,OK,Normale
231,M0026,2026-01-06 01:00:00,C002,B001,22.87,77.99,1010.15,213.19,OK,Normale
355,M0147,2026-01-11 02:00:00,C003,B001,26.14,84.97,1003.59,142.31,OK,Normale
538,M0456,2026-01-23 23:00:00,C012,B004,20.68,72.69,1022.77,309.01,OK,Normale
539,M0302,2026-01-17 13:00:00,C002,B001,22.05,58.26,1007.30,140.42,OK,Normale

### 3) Supprimer les doublons puis vérifier la suppression

In [50]:
print("Avant suppression :", df.duplicated().sum(), "doublons")
df = df.drop_duplicates()
print("Après suppression :", df.duplicated().sum(), "doublons")
print("Taille finale :", df.shape)

Avant suppression : 5 doublons
Après suppression : 0 doublons
Taille finale : (600, 10)

## Partie 11 – Statistiques descriptives

### 1) Température : min, max, moyenne, médiane, écart-type et nombre de valeurs

In [51]:
df["temperature"].agg(["min", "max", "mean", "median", "std", "count"])

min       -18.500000
max        58.700000
mean       24.896033
median     24.878314
std         4.048027
count     600.000000
Name: temperature, dtype: float64

### 2) "etat" : mode et nombre de mesures par état (OK, ALERTE, ERREUR)

In [52]:
mode_etat = df["etat"].mode()
print("Mode de l'état :", mode_etat.tolist())
print()
df["etat"].value_counts()

Mode de l'état : ['OK']

etat
OK         562
ALERTE      29
ERREUR       5
INCONNU      4
Name: count, dtype: int64

## Partie 12 – Exportation

Le dataframe `df` est maintenant nettoyé (valeurs manquantes comblées, doublons supprimés).

### 1) Exporter dans `exports/donnees_nettoyees.csv`

In [53]:
df.to_csv("../exports/donnees_nettoyees.csv", index=False)
print("Export CSV terminé")

Export CSV terminé

### 2) Exporter dans `exports/donnees_nettoyees.json`

In [54]:
df.to_json("../exports/donnees_nettoyees.json", orient="records", indent=2, force_ascii=False)
print("Export JSON terminé")

Export JSON terminé