# Atelier Pandas – Données IoT

Préparation et analyse de mesures issues de capteurs IoT (température, humidité, pression, consommation) avant transmission à un système de Machine Learning.

## Partie 1 – Series

### 1) Créer une Series contenant 4 températures

In [1]:
import pandas as pd

serie_temp = pd.Series([24.5, 25.1, 26.3, 27.8])
serie_temp

0    24.5
1    25.1
2    26.3
3    27.8
dtype: float64

### 2) Afficher son index

In [2]:
serie_temp.index

RangeIndex(start=0, stop=4, step=1)

### 3) Afficher la 1ère valeur

In [3]:
serie_temp.iloc[0]

np.float64(24.5)

### 4) Afficher la dernière valeur

In [4]:
serie_temp.iloc[-1]

np.float64(27.8)

### 5) Créer, de deux façons différentes, une Series de 4 températures avec les heures de mesure 12h, 13h, 14h et 15h comme index

**Méthode 1 :** passer l'index en paramètre

In [5]:
temps = [24.5, 25.1, 26.3, 27.8]
heures = [12, 13, 14, 15]

serie_heures = pd.Series(temps, index=heures)
serie_heures

12    24.5
13    25.1
14    26.3
15    27.8
dtype: float64

**Méthode 2 :** passer un dictionnaire

In [6]:
serie_heures2 = pd.Series({12: 24.5, 13: 25.1, 14: 26.3, 15: 27.8})
serie_heures2

12    24.5
13    25.1
14    26.3
15    27.8
dtype: float64

### 6) Afficher la 1ère et la dernière valeur

In [7]:
premiere = serie_heures.iloc[0]
derniere = serie_heures.iloc[-1]
print(f"1ère valeur : {premiere}")
print(f"Dernière valeur : {derniere}")

1ère valeur : 24.5
Dernière valeur : 27.8

## Partie 2 – DataFrame

### 1) Créer et afficher le dataframe `df_test` à partir du dictionnaire

In [8]:
data = {
    "capteur": ["C001", "C002", "C003"],
    "temperature": [24.5, 25.1, 26.3],
    "humidite": [65, 67, 70]
}

df_test = pd.DataFrame(data)
df_test

  capteur  temperature  humidite
0    C001         24.5        65
1    C002         25.1        67
2    C003         26.3        70

### 2) Importer le dataset `mesures_capteurs.csv` dans le dataframe `df`

In [9]:
df = pd.read_csv("../data/mesures_capteurs.csv")
df

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK
...,...,...,...,...,...,...,...,...,...
600,M0072,2026-01-07 23:00:00,C012,B004,23.67,60.28,1015.11,282.36,OK
601,M0107,2026-01-09 10:00:00,C011,B004,24.34,61.42,1019.43,357.43,OK
602,M0271,2026-01-16 06:00:00,C007,B003,23.73,63.49,1016.46,152.79,OK
603,M0436,2026-01-23 03:00:00,C004,B002,24.83,79.77,1017.05,170.97,OK
604,M0103,2026-01-09 06:00:00,C007,B003,17.02,52.04,1001.14,44.99,OK

### 3) Afficher les dimensions de `df`

In [10]:
print(f"{df.shape[0]} lignes et {df.shape[1]} colonnes")

605 lignes et 9 colonnes

## Partie 3 – Exploration

Dans la suite de l'atelier, on travaille avec le dataframe `df`.

### 1) Afficher les premières lignes

In [11]:
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

### 2) Afficher les 10 premières lignes

In [12]:
df.head(10)

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK
5,M0595,2026-01-29 18:00:00,C007,B003,24.51,58.01,1013.34,146.10,OK
6,M0011,2026-01-05 10:00:00,C011,B004,29.23,70.43,1007.68,290.45,OK
7,M0132,2026-01-10 11:00:00,C012,B004,31.21,60.57,1024.64,285.92,OK
8,M0444,2026-01-23 11:00:00,C012,B004,23.11,82.06,1021.96,293.36,OK
9,M0087,2026-01-08 14:00:00,C003,B001,28.85,44.37,1008.27,206.59,OK

### 3) Afficher les dernières lignes

In [13]:
df.tail()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
600,M0072,2026-01-07 23:00:00,C012,B004,23.67,60.28,1015.11,282.36,OK
601,M0107,2026-01-09 10:00:00,C011,B004,24.34,61.42,1019.43,357.43,OK
602,M0271,2026-01-16 06:00:00,C007,B003,23.73,63.49,1016.46,152.79,OK
603,M0436,2026-01-23 03:00:00,C004,B002,24.83,79.77,1017.05,170.97,OK
604,M0103,2026-01-09 06:00:00,C007,B003,17.02,52.04,1001.14,44.99,OK

### 4) Afficher le nombre de lignes

In [14]:
df.shape[0]

605

### 5) Afficher le nombre de colonnes

In [15]:
df.shape[1]

9

### 6) Afficher les noms des colonnes

In [16]:
df.columns

Index(['id_mesure', 'date_heure', 'id_capteur', 'batiment', 'temperature',
       'humidite', 'pression', 'consommation', 'etat'],
      dtype='object')

### 7) Afficher les informations générales

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_mesure     605 non-null    object
 1   date_heure    605 non-null    object
 2   id_capteur    605 non-null    object
 3   batiment      605 non-null    object
 4   temperature   599 non-null    float64
 5   humidite      600 non-null    float64
 6   pression      600 non-null    float64
 7   consommation  600 non-null    float64
 8   etat          601 non-null    object
dtypes: float64(4), object(5)
memory usage: 42.7+ KB

### 8) Afficher les statistiques descriptives

In [18]:
df.describe()

       temperature   humidite     pression  consommation
count   599.000000  600.00000   600.000000    600.000000
mean     24.878314   64.92620  1012.221900    208.675417
std       4.059576   10.76905    10.599042     72.243567
min     -18.500000   28.52000   850.000000     18.120000
25%      22.570000   58.17250  1006.790000    160.177500
50%      24.860000   65.37500  1012.855000    206.150000
75%      27.275000   71.61500  1017.827500    254.127500
max      58.700000  145.00000  1038.430000    875.000000